---
- name: Run a specified Bash script on remote hosts
  hosts: all
  become: yes

  vars:
    # Provide a default path if no extra_var is passed
    script: "/tmp/script.sh"

  tasks:
    - name: Copy the script to remote hosts
      copy:
        src: "{{ script }}"
        dest: "/tmp/myscript.sh"
        mode: "0755"

    - name: Execute the script on the remote hosts
      command: "/tmp/myscript.sh"
